CREATE TABLE IF NOT EXISTS ava_stock_product_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code VARCHAR(60) NOT NULL UNIQUE,
    model_name VARCHAR(150) NOT NULL,
    description TEXT,
    image_url TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_code VARCHAR(100) NOT NULL UNIQUE,
    part_name VARCHAR(150) NOT NULL,
    unit VARCHAR(20) NOT NULL DEFAULT 'EA',
    image_url TEXT,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_bom_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT NOT NULL REFERENCES ava_stock_product_models(id),
    version_no INTEGER NOT NULL,
    version_name VARCHAR(100),
    current_version BOOLEAN NOT NULL DEFAULT FALSE,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_ava_stock_bom_versions_model_version UNIQUE (model_id, version_no)
);

CREATE TABLE IF NOT EXISTS ava_stock_bom_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_version_id BIGINT NOT NULL REFERENCES ava_stock_bom_versions(id),
    model_id BIGINT NOT NULL REFERENCES ava_stock_product_models(id),
    part_id BIGINT NOT NULL REFERENCES ava_stock_parts(id),
    item_label VARCHAR(150),
    default_qty INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 1,
    required_flag BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_ava_stock_bom_items_version_part UNIQUE (bom_version_id, part_id),
    CONSTRAINT uk_ava_stock_bom_items_version_sort UNIQUE (bom_version_id, sort_order)
);

CREATE TABLE IF NOT EXISTS ava_stock_part_qr_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id BIGINT NOT NULL REFERENCES ava_stock_parts(id),
    qr_value VARCHAR(255) NOT NULL UNIQUE,
    label VARCHAR(150),
    location_code VARCHAR(80),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_product_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(150),
    received_date DATE NOT NULL DEFAULT CURRENT_DATE,
    memo TEXT,
    created_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_product_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT NOT NULL REFERENCES ava_stock_product_models(id),
    bom_version_id BIGINT NOT NULL REFERENCES ava_stock_bom_versions(id),
    receipt_id BIGINT REFERENCES ava_stock_product_receipts(id),
    serial_no VARCHAR(120) NOT NULL UNIQUE,
    qr_value VARCHAR(255) NOT NULL UNIQUE,
    current_status VARCHAR(30) NOT NULL DEFAULT 'SEMI_RECEIVED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_service_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_unit_id BIGINT NOT NULL REFERENCES ava_stock_product_units(id),
    service_no VARCHAR(120) NOT NULL UNIQUE,
    service_status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    issue_summary TEXT,
    received_date DATE NOT NULL DEFAULT CURRENT_DATE,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    saved_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_product_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_unit_id BIGINT NOT NULL REFERENCES ava_stock_product_units(id),
    bom_version_id BIGINT NOT NULL REFERENCES ava_stock_bom_versions(id),
    service_case_id BIGINT REFERENCES ava_stock_service_cases(id),
    operation_type VARCHAR(30) NOT NULL,
    operation_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    saved_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_by UUID,
    completed_by UUID,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS ava_stock_operation_check_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL REFERENCES ava_stock_product_operations(id),
    bom_version_id BIGINT NOT NULL REFERENCES ava_stock_bom_versions(id),
    bom_item_id BIGINT NOT NULL REFERENCES ava_stock_bom_items(id),
    part_id BIGINT NOT NULL REFERENCES ava_stock_parts(id),
    check_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    qty_used INTEGER NOT NULL DEFAULT 0,
    checked_at TIMESTAMPTZ,
    checked_by UUID,
    memo TEXT,
    CONSTRAINT uk_ava_stock_operation_check_items_operation_bom UNIQUE (operation_id, bom_item_id)
);

CREATE TABLE IF NOT EXISTS ava_stock_part_stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id BIGINT NOT NULL REFERENCES ava_stock_parts(id),
    part_qr_id BIGINT REFERENCES ava_stock_part_qr_codes(id),
    product_unit_id BIGINT REFERENCES ava_stock_product_units(id),
    service_case_id BIGINT REFERENCES ava_stock_service_cases(id),
    operation_id BIGINT REFERENCES ava_stock_product_operations(id),
    check_item_id BIGINT REFERENCES ava_stock_operation_check_items(id),
    movement_type VARCHAR(30) NOT NULL,
    qty_delta INTEGER NOT NULL,
    memo TEXT,
    created_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_finished_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_unit_id BIGINT NOT NULL UNIQUE REFERENCES ava_stock_product_units(id),
    manufacturing_operation_id BIGINT NOT NULL UNIQUE REFERENCES ava_stock_product_operations(id),
    finished_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_by UUID
);

CREATE TABLE IF NOT EXISTS ava_stock_destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_name VARCHAR(150) NOT NULL UNIQUE,
    country VARCHAR(80),
    city VARCHAR(80),
    address TEXT,
    contact_name VARCHAR(100),
    contact_phone VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT NOT NULL REFERENCES ava_stock_destinations(id),
    shipment_type VARCHAR(30) NOT NULL DEFAULT 'OUTBOUND',
    shipping_method VARCHAR(200) NOT NULL,
    shipping_date DATE NOT NULL,
    shipment_status VARCHAR(30) NOT NULL DEFAULT 'IN_TRANSIT',
    tracking_no VARCHAR(120),
    memo TEXT,
    created_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ava_stock_shipment_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES ava_stock_shipments(id),
    product_unit_id BIGINT NOT NULL REFERENCES ava_stock_product_units(id),
    item_status VARCHAR(30) NOT NULL DEFAULT 'INCLUDED',
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_ava_stock_shipment_items_shipment_product UNIQUE (shipment_id, product_unit_id)
);

CREATE TABLE IF NOT EXISTS ava_stock_product_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_unit_id BIGINT NOT NULL REFERENCES ava_stock_product_units(id),
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    reason VARCHAR(150),
    ref_type VARCHAR(40),
    ref_id BIGINT,
    changed_by UUID,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ava_stock_product_units_status ON ava_stock_product_units(current_status);
CREATE INDEX IF NOT EXISTS idx_ava_stock_product_units_qr ON ava_stock_product_units(qr_value);
CREATE INDEX IF NOT EXISTS idx_ava_stock_part_qr_codes_qr ON ava_stock_part_qr_codes(qr_value);
CREATE INDEX IF NOT EXISTS idx_ava_stock_movements_part_created ON ava_stock_part_stock_movements(part_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ava_stock_movements_product ON ava_stock_part_stock_movements(product_unit_id);
CREATE INDEX IF NOT EXISTS idx_ava_stock_shipments_date ON ava_stock_shipments(shipping_date DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ava_stock_status_history_product ON ava_stock_product_status_history(product_unit_id, changed_at DESC);
